# Generated by Django 4.2.23 on 2025-10-21 12:40

from django.db import migrations


def convert_nulls_to_empty(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")

    # Update Profile text fields
    Profile.objects.filter(first_name__isnull=True).update(first_name="")
    Profile.objects.filter(last_name__isnull=True).update(last_name="")
    Profile.objects.filter(artist_name__isnull=True).update(artist_name="")
    Profile.objects.filter(company_name__isnull=True).update(company_name="")
    Profile.objects.filter(personal_website__isnull=True).update(personal_website="")
    Profile.objects.filter(location__isnull=True).update(location="")
    Profile.objects.filter(nationality__isnull=True).update(nationality="")
    Profile.objects.filter(instagram_profile__isnull=True).update(instagram_profile="")
    Profile.objects.filter(facebook_profile__isnull=True).update(facebook_profile="")
    Profile.objects.filter(tiktok_profile__isnull=True).update(tiktok_profile="")
    Profile.objects.filter(youtube_profile__isnull=True).update(youtube_profile="")


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_phone"),
    ]

    operations = [
        migrations.RunPython(
            convert_nulls_to_empty, reverse_code=migrations.RunPython.noop
        ),
    ]
