# Generated by Django 4.2.23 on 2025-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_profile_spoken_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_host_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_host_user",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_use_tls",
            field=models.BooleanField(default=True),
        ),
    ]
