# Generated by Django 4.2.23 on 2025-12-26 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_profile_other_email_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
    ]
