# Generated by Django 4.2.23 on 2026-01-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_emailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='text',
            new_name='content',
        ),
    ]
