# Generated by Django 4.2.23 on 2026-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_profile_date_format_profile_table_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="confirmed_account",
            field=models.BooleanField(default=False),
        ),
    ]
