# Generated by Django 4.2.23 on 2026-02-25 12:57

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_profile_confirmation_token_profile_confirmed_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_host_password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
