# Generated by Django 6.0.3 on 2026-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_profile_google_oauth_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="current_application_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
