# Generated by Django 6.0.3 on 2026-03-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_add_current_application_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="default_email_subject",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
