# Generated by Django 4.2.23 on 2025-10-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('applications', '0003_application_performances_application_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='festival',
        ),
        migrations.AddField(
            model_name='application',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='application',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
