# Generated by Django 4.2.23 on 2025-10-11 10:24

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def populate_content_type(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    Festival = apps.get_model("festivals", "Festival")

    festival_ct = ContentType.objects.get_for_model(Festival)

    Application.objects.filter(content_type__isnull=True).update(
        content_type=festival_ct
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0004_remove_application_festival_application_content_type_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_content_type, migrations.RunPython.noop),
    ]
