# Generated by Django 4.2.23 on 2025-10-21 12:40

from django.db import migrations


def convert_nulls_to_empty(apps, schema_editor):
    Application = apps.get_model("applications", "Application")

    # Update Application text fields
    Application.objects.filter(application_method__isnull=True).update(
        application_method=""
    )
    Application.objects.filter(email_subject__isnull=True).update(email_subject="")
    Application.objects.filter(message__isnull=True).update(message="")
    Application.objects.filter(response_details__isnull=True).update(
        response_details=""
    )
    Application.objects.filter(performance_details__isnull=True).update(
        performance_details=""
    )
    Application.objects.filter(comments__isnull=True).update(comments="")


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0005_populate_content_type"),
    ]

    operations = [
        migrations.RunPython(
            convert_nulls_to_empty, reverse_code=migrations.RunPython.noop
        ),
    ]
