# Generated by Django 4.2.23 on 2025-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0006_convert_text_nulls_to_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMAIL", "Email"),
                    ("FORM", "Form"),
                    ("INVITATION_ONLY", "Invitation only"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="EMAIL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="comments",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="email_subject",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="message",
            field=models.CharField(blank=True, default="", max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="performance_details",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="response_details",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
