# Generated by Django 4.2.23 on 2025-12-15 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0009_remove_application_answer_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="application_status",
            new_name="status",
        ),
    ]
