# Generated by Django 4.2.23 on 2026-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0010_rename_application_status_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
