# Generated by Django 6.0.3 on 2026-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0011_application_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="application_year_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
