# Generated by Django 4.2.23 on 2025-07-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0004_rename_date_text_festival_approximate_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="application_date_end",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="application_date_start",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
