# Generated by Django 4.2.23 on 2025-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0005_festival_application_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("FORM", "Form"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
    ]
