# Generated by Django 4.2.23 on 2025-08-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0006_festival_application_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("FORM", "Form"),
                    ("INVITATION_ONLY", "Invitation only"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
    ]
