# Generated by Django 4.2.23 on 2025-10-08 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0008_alter_festival_application_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="festival",
            name="applied",
        ),
    ]
