# Generated by Django 4.2.23 on 2025-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0010_rename_festival_name_festival_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="application_date_end",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="application_date_start",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="application_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMAIL", "Email"),
                    ("FORM", "Form"),
                    ("INVITATION_ONLY", "Invitation only"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="approximate_date",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="comments",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="festival_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STREET", "Street"),
                    ("PUPPET", "Puppet"),
                    ("JUGGLING_CONVENTION", "Juggling convention"),
                    ("CIRCUS", "Circus"),
                    ("MUSIC", "Music"),
                    ("THEATRE", "Theatre"),
                    ("DANCE", "Dance"),
                    ("OTHER", "Other"),
                ],
                default="STREET",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="town",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festival",
            name="website_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festivalcontact",
            name="email",
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="festivalcontact",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festivalcontact",
            name="role",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
