# Generated by Django 4.2.23 on 2026-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0013_alter_festival_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="festivalcontact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
