# Generated by Django 4.2.23 on 2026-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festivals", "0016_festival_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalcontact",
            name="is_seed_clone",
            field=models.BooleanField(default=False),
        ),
    ]
