# Generated by Django 4.2.23 on 2025-10-03 09:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_alter_performance_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CIRCUS', 'Circus'), ('JUGGLING', 'Juggling'), ('COMEDY', 'Comedy'), ('CLOWN', 'Clown'), ('MIME', 'Mime'), ('STANDUP', 'Stand up'), ('PUPPETRY', 'Puppetry'), ('WALK_ACT', 'Walk Act'), ('FIRE_SHOW', 'Fire Show'), ('MUSIC', 'Live Music'), ('DANCE', 'Dance / Physical Theatre'), ('THEATRE', 'Theatre / Drama'), ('MAGIC', 'Magic / Illusion'), ('INSTALLATION', 'Installation / Interactive Art'), ('KIDS', 'Kids / Family Show'), ('MULTIMEDIA', 'Multimedia / Projection')], max_length=124),
        ),
    ]
