# Generated by Django 4.2.23 on 2025-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_alter_performance_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='email_prompt',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
