# Generated by Django 4.2.23 on 2025-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0008_convert_text_nulls_to_empty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performance",
            name="dossier",
        ),
        migrations.AlterField(
            model_name="performance",
            name="email_prompt",
            field=models.TextField(blank=True, default="", max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="performance",
            name="long_description",
            field=models.TextField(blank=True, default="", max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="performance",
            name="performance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STREET", "Street show"),
                    ("INDOOR_STAGE", "Indoor stage"),
                    ("OUTDOOR", "Outdoor"),
                    ("INSTALLATION", "Installation"),
                    ("WALK_ACT", "Walk act"),
                    ("FIRE_SHOW", "Fire show"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="performance",
            name="short_description",
            field=models.TextField(blank=True, default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="performance",
            name="trailer",
            field=models.URLField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
