# Generated by Django 6.0.3 on 2026-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_remove_performance_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='length',
            field=models.CharField(blank=True, null=True),
        ),
    ]
