FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS base
ARG APP_HOME=/app

FROM base AS deps
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR ${APP_HOME}

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

FROM base AS build
WORKDIR ${APP_HOME}

COPY . .
# RUN .venv/bin/python manage.py collectstatic --noinput

FROM base AS run
WORKDIR ${APP_HOME}

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PATH="/app/.venv/bin:$PATH"

RUN apt-get update && apt-get install -y \
    postgresql-client \
    curl \
    && rm -rf /var/lib/apt/lists/*


RUN addgroup --system --gid 999 django && \
    adduser --system --uid 999 --gid 999 django

COPY --from=deps --chown=django:django /app/.venv ./.venv
COPY --from=build --chown=django:django /app/docker/entrypoint.sh .
COPY --from=build --chown=django:django /app .

RUN chmod +x /app/entrypoint.sh

USER django

EXPOSE 8000

ENTRYPOINT [ "/app/entrypoint.sh" ]