# Generated by Django 4.2.23 on 2025-09-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("residency_name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("town", models.CharField(blank=True, max_length=100, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "approximate_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "application_date_start",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "application_date_end",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "application_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMAIL", "Email"),
                            ("FORM", "Form"),
                            ("OPEN_CALL", "Open call"),
                            ("INVITATION_ONLY", "Invitation only"),
                            ("OTHER", "Other"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
