# Generated by Django 4.2.23 on 2025-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residencies", "0002_rename_residency_name_residency_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residency",
            name="application_date_end",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="application_date_start",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="application_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMAIL", "Email"),
                    ("FORM", "Form"),
                    ("OPEN_CALL", "Open call"),
                    ("INVITATION_ONLY", "Invitation only"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="residency",
            name="approximate_date",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="comments",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="town",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residency",
            name="website_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residencycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="residencycontact",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residencycontact",
            name="role",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
