# Generated by Django 4.2.23 on 2026-02-16 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("residencies", "0006_residency_deleted_at_residencycontact_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="residencycontact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
