# Generated by Django 4.2.23 on 2026-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residencies", "0009_residencycontact_is_seed_clone"),
    ]

    operations = [
        migrations.AddField(
            model_name="residency",
            name="is_seed_clone",
            field=models.BooleanField(default=False),
        ),
    ]
