# Generated by Django 4.2.23 on 2025-10-11 10:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='contact_person',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venues_venue',
        ),
        migrations.CreateModel(
            name='VenueContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='venues.venue')),
            ],
            options={
                'db_table': 'venues_venuecontact',
            },
        ),
    ]
