# Generated by Django 4.2.23 on 2025-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_rename_venue_name_venue_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="comments",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="town",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="venue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("THEATRE", "Theatre"),
                    ("OPERA_HOUSE", "Opera house"),
                    ("CONCERT_HALL", "Concert hall"),
                    ("DANCE_STUDIO", "Dance studio"),
                    ("MUSIC_VENUE", "Music venue"),
                    ("CIRCUS_TENT", "Circus tent"),
                    ("PERFORMANCE_SPACE", "Performance space"),
                    ("ART_GALLERY", "Art gallery"),
                    ("OUTDOOR_STAGE", "Outdoor stage"),
                    ("PUPPET_THEATRE", "Puppet theatre"),
                    ("CIRCUS_SPACE", "Circus space"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="website_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venuecontact",
            name="email",
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="venuecontact",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venuecontact",
            name="role",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
