# Generated by Django 4.2.23 on 2026-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0005_alter_venue_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="venuecontact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
